# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 4) do

  create_table "categories", :force => true do |t|
    t.column "name",            :string,                  :null => false
    t.column "description",     :text
    t.column "subcategory",     :integer,  :default => 0, :null => false
    t.column "number_of_links", :integer,  :default => 0, :null => false
    t.column "created_on",      :datetime,                :null => false
    t.column "updated_on",      :datetime,                :null => false
  end

  create_table "domains", :force => true do |t|
    t.column "title",           :text
    t.column "scheme",          :string,                  :null => false
    t.column "domain",          :string,                  :null => false
    t.column "favicon",         :integer,  :default => 0, :null => false
    t.column "number_of_links", :integer,  :default => 0, :null => false
    t.column "created_on",      :datetime,                :null => false
    t.column "updated_on",      :datetime,                :null => false
  end

  create_table "links", :force => true do |t|
    t.column "member_id",   :integer,  :null => false
    t.column "domain_id",   :integer,  :null => false
    t.column "category_id", :integer
    t.column "title",       :text,     :null => false
    t.column "uri",         :text,     :null => false
    t.column "path",        :text
    t.column "variables",   :text
    t.column "code",        :string,   :null => false
    t.column "created_on",  :datetime, :null => false
    t.column "updated_on",  :datetime, :null => false
  end

  create_table "members", :force => true do |t|
    t.column "username",      :string,   :null => false
    t.column "password",      :string,   :null => false
    t.column "first_name",    :string,   :null => false
    t.column "last_name",     :string,   :null => false
    t.column "email_address", :string,   :null => false
    t.column "created_on",    :datetime, :null => false
    t.column "updated_on",    :datetime, :null => false
  end

end
