# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 3) do

  create_table "categories", :force => true do |t|
  end

  create_table "links", :force => true do |t|
  end

  create_table "members", :force => true do |t|
    t.column "username",      :string,   :default => "", :null => false
    t.column "password",      :string,   :default => "", :null => false
    t.column "first_name",    :string,   :default => "", :null => false
    t.column "last_name",     :string,   :default => "", :null => false
    t.column "email_address", :string,   :default => "", :null => false
    t.column "created_on",    :datetime,                 :null => false
    t.column "updated_on",    :datetime,                 :null => false
  end

end
